# -*- coding: UTF-8 -*-
'''
@Project ：SE4GEO 
@File    ：attributes_descriptions.py
@IDE     ：PyCharm 
@Author  ：JUNJIE MU
@Date    ：2024/6/25 下午9:32 
@explain : 
'''

flood_descriptions = {
    'cod_rip': 'Surface area of areas with high flood risk (km2)',
    'ar_id_p3': 'Surface area of areas with medium flood risk (km2)',
    'ar_id_p2': 'Surface area of low flood risk areas (km2)',
    'ar_id_p1': 'Surface area of areas with high flood risk (%)',
    'aridp3_p': 'Surface area of areas with medium flood risk (%)',
    'aridp2_p': 'Surface area of areas with low flood risk (%)',
    'pop_res011': 'Resident population - 2011 Census (no. of inhabitants)',
    'pop_idr_p3': 'Population at high flood risk (no. of inhabitants)',
    'pop_idr_p2': 'Population at medium flood risk (no. of inhabitants)',
    'pop_idr_p1': 'Population at low flood risk (no. of inhabitants)',
    'popidp3_p': 'Population at high flood risk (%)',
    'popidp2_p': 'Population at medium flood risk (%)',
    'popidp1_p': 'Population at low flood risk (%)',
    'fam_tot': 'Families - 2011 Census (n.)',
    'fam_idr_p3': 'Families at high flood risk (n.)',
    'fam_idr_p2': 'Families at medium flood risk (n.)',
    'fam_idr_p1': 'Families at low flood risk (n.)',
    'famidp3_p': 'Families at high flood risk (%)',
    'famidp2_p': 'Families at medium flood risk (%)',
    'famidp1_p': 'Families at low flood risk (%)',
    'ed_tot': 'Buildings - 2011 Census (n.)',
    'ed_idr_p3': 'Buildings at high flood risk (n.)',
    'ed_idr_p2': 'Buildings at medium flood risk (n.)',
    'ed_idr_p1': 'Buildings at low flood risk (n.)',
    'edidp3_p': 'Buildings at high flood risk (%)',
    'edidp2_p': 'Buildings at medium flood risk (%)',
    'edidp1_p': 'Buildings at low flood risk (%)',
    'im_tot': 'Local business units - 2011 Census (n.)',
    'im_idr_p3': 'Local business units at high flood risk (n.)',
    'im_idr_p2': 'Local business units at medium flood risk (n.)',
    'im_idr_p1': 'Local business units at low flood risk (n.)',
    'imidp3_p': 'Local business units at high flood risk (%)',
    'imidp2_p': 'Local business units at medium flood risk (%)',
    'imidp1_p': 'Local business units at low flood risk (%)',
    'n_vir': 'Cultural heritage - Constraints on the VIR Network (n.)',
    'bbcc_id_p3': 'Cultural heritage at high flood risk (n.)',
    'bbcc_id_p2': 'Cultural heritage at medium flood risk (n.)',
    'bbcc_id_p1': 'Cultural heritage at low flood risk (n.)',
    'bbccidp3_p': 'Cultural heritage at high flood risk (%)',
    'bbccidp2_p': 'Cultural heritage at medium flood risk (%)',
    'bbccidp1_p': 'Cultural heritage at low flood risk (%)'
}

landslide_descriptions = {
    'ar_fr_p4': 'Surface area of areas with very high landslide risk P4 (km2)',
    'ar_fr_p3': 'Surface area of areas with high landslide risk P3 (km2)',
    'ar_fr_p2': 'Surface area of average landslide risk areas P2 (km2)',
    'ar_fr_p1': 'Surface area of areas with moderate landslide risk P1 (km2)',
    'ar_fr_aa': 'Surface area of AA attention areas (km2)',
    'ar_fr_p3p4': 'Surface area of areas with very high and very high landslide risk (P4 + P3) (km2)',
    'ar_frp4_p': 'Surface area of areas with very high landslide risk P4 (%)',
    'ar_frp3_p': 'Surface area of areas with high landslide risk P3 (%)',
    'ar_frp2_p': 'Surface area of areas with medium landslide risk P2 (%)',
    'ar_frp1_p': 'Surface area of areas with moderate landslide risk P1 (%)',
    'ar_fraa_p': 'Surface area of AA attention areas (%)',
    'ar_frp3p4p': 'Surface area of areas with very high and very high landslide risk (P4 + P3) (%)',
    'pop_fr_p4': 'Population at very high landslide risk P4 (no. of inhabitants)',
    'pop_fr_p3': 'Population at high landslide risk P3 (no. of inhabitants)',
    'pop_fr_p2': 'Population at medium landslide risk P2 (no. of inhabitants)',
    'pop_fr_p1': 'Population at moderate landslide risk P1 (no. of inhabitants)',
    'pop_fr_aa': 'Population at risk in AA attention areas (no. of inhabitants)',
    'popfr_p3p4': 'Population at very high and very high landslide risk (P4 + P3) (no. of inhabitants)',
    'popfrp4_p': 'Population at very high landslide risk P4 (%)',
    'popfrp3_p': 'Population at high landslide risk P3 (%)',
    'popfrp2_p': 'Population at medium landslide risk P2 (%)',
    'popfrp1_p': 'Population at moderate landslide risk P1 (%)',
    'popfraa_p': 'Population at risk in AA focus areas (%)',
    'popfrp3p4p': 'Population at very high and very high landslide risk (P4 + P3) (%)',
    'fam_fr_p4': 'Families at very high landslide risk P4 (n.)',
    'fam_fr_p3': 'Families at high landslide risk P3 (n.)',
    'fam_fr_p2': 'Families at medium landslide risk P2 (n.)',
    'fam_fr_p1': 'Families at moderate landslide risk P1 (n.)',
    'fam_fr_aa': 'Families at risk in AA attention areas (n.)',
    'famfr_p3p4': 'Families at very high and very high landslide risk (P4 + P3) (n.)',
    'famfrp4_p': 'Families at risk in landslide-prone areas',
    'famfrp3_p': 'Families at risk in areas with high landslide risk P3 (%)',
    'famfrp2_p': 'Families at risk in areas with medium landslide risk P2 (%)',
    'famfrp1_p': 'Families at risk in areas with moderate landslide risk P1 (%)',
    'famfraa_p': 'Families at risk in AA attention areas (%)',
    'famfrp3p4p': 'Families at risk in areas with very high and very high landslide risk (P4 + P3) (%)',
    'ed_fr_p4': 'Buildings at risk in areas with very high landslide risk P4 (n.)',
    'ed_fr_p3': 'Buildings at risk in areas with high landslide risk P3 (n.)',
    'ed_fr_p2': 'Buildings at risk in areas with medium landslide risk P2 (n.)',
    'ed_fr_p1': 'Buildings at risk in areas with moderate landslide risk P1 (n.)',
    'ed_fr_aa': 'Buildings at risk in AA attention areas (n.)',
    'ed_fr_p3p4': 'Buildings at risk in areas with very high and very high landslide risk (P4 + P3) (n.)',
    'edfrp4_p': 'Buildings at risk in areas with very high landslide risk P4 (%)',
    'edfrp3_p': 'Buildings at risk in areas with high landslide risk P3 (%)',
    'edfrp2_p': 'Buildings at risk in areas with medium landslide risk P2 (%)',
    'edfrp1_p': 'Buildings at risk in areas with moderate landslide risk P1 (%)',
    'edfraa_p': 'Buildings at risk in AA attention areas (%)',
    'edfrp3p4p': 'Buildings at risk in areas with very high and very high landslide risk (P4 + P3) (%)',
    'im_fr_p4': 'Local business units at risk in areas with very high landslide risk P4 (n.)',
    'im_fr_p3': 'Local business units at risk in areas with high landslide risk P3 (n.)',
    'im_fr_p2': 'Local business units at risk in areas with medium landslide risk P2 (n.)',
    'im_fr_p1': 'Local business units at risk in areas with moderate landslide risk P1 (n.)',
    'im_fr_aa': 'Local business units at risk in AA attention areas (n.)',
    'imfr_p3p4': 'Local business units at risk in areas with very high and very high landslide risk (P4 + P3) (n.)',
    'imfrp4_p': 'Local business units at risk in areas with very high landslide risk P4 (%)',
    'imfrp3_p': 'Local business units at risk in areas with high landslide risk P3 (%)',
    'imfrp2_p': 'Local business units at risk in areas with medium landslide risk P2 (%)',
    'imfrp1_p': 'Local business units at risk in areas with moderate landslide risk P1 (%)',
    'imfraa_p': 'Local business units at risk in AA attention areas (%)',
    'imfrp3p4p': 'Local business units at risk in areas with very high and very high landslide risk (P4 + P3) (%)',
    'bbcc_fr_p4': 'Cultural heritage at risk in areas with very high landslide risk P4 (n.)',
    'bbcc_fr_p3': 'Cultural heritage at risk in areas with high landslide risk P3 (n.)',
    'bbcc_fr_p2': 'Cultural heritage at risk in medium landslide risk areas P2 (n.)',
    'bbcc_fr_p1': 'Cultural heritage at risk in areas with moderate landslide risk P1 (n.)',
    'bbcc_fr_aa': 'Cultural heritage at risk in areas of AA attention (n.)',
    'bbccfrp3p4': 'Cultural heritage at risk in areas with very high and very high landslide risk (P4 + P3) (n.)',
    'bbccfrp4_p': 'Cultural heritage at risk in areas with very high landslide risk P4 (%)',
    'bbccfrp3_p': 'Cultural heritage at risk in areas with high landslide risk P3 (%)',
    'bbccfrp2_p': 'Cultural heritage at risk in areas with medium landslide risk P2 (%)',
    'bbccfrp1_p': 'Cultural heritage at risk in areas with moderate landslide risk P1 (%)',
    'bbccfraa_p': 'Cultural heritage at risk in AA attention areas (%)',
    'bbccfrp34p': 'Cultural heritage at risk in areas with very high and very high landslide risk (P4 + P3) (%)',
}
